export { isVue2, isVue3 } from 'vue-demi';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, defineNuxtComponent, useNuxtApp, defineNuxtPlugin, definePayloadPlugin, reloadNuxtApp, useRuntimeConfig, useState, clearNuxtState, useFetch, useLazyFetch, useCookie, useRequestHeaders, useRequestEvent, useRequestFetch, useRequestURL, setResponseStatus, setPageLayout, onNuxtReady, useRouter, useRoute, defineNuxtRouteMiddleware, navigateTo, abortNavigation, addRouteMiddleware, showError, clearError, isNuxtError, useError, createError, defineNuxtLink, useAppConfig, updateAppConfig, defineAppConfig, preloadComponents, preloadRouteComponents, prefetchComponents, loadPayload, preloadPayload, isPrerendered, definePayloadReducer, definePayloadReviver, requestIdleCallback, cancelIdleCallback } from '#app';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from '#vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, defineModel, defineOptions, defineSlots, mergeModels, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, Component, ComponentPublicInstance, ComputedRef, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode } from 'vue';
export { Notification, Message, Modal, useFormItem } from '@arco-design/web-vue/es';
export { injectHead, useHead, useSeoMeta, useHeadSafe, useServerHead, useServerSeoMeta, useServerHeadSafe } from '@unhead/vue';
export { useTable, useForm, useModal, TableCustomColumnData } from '../composables/useArco';
export { default as useBasicsMap } from '../composables/useBasicsMap';
export { default as useBasicsSet } from '../composables/useBasicsSet';
export { default as useBasicsState } from '../composables/useBasicsState';
export { useCountDown } from '../composables/useCountDown';
export { default as useInitRequest } from '../composables/useInitRequest';
export { default as useLoading } from '../composables/useLoading';
export { default as useOriginalState } from '../composables/useOriginalState';
export { default as usePagination } from '../composables/usePagination';
export { default as useRequest } from '../composables/useRequest';
export { Local, Session } from '../composables/useStorage';
export { default as useUser } from '../composables/useUser';
export { default as useWebsiteInformation } from '../composables/useWebsiteInformation';
export { sleep, textFormat, textCompany, formatDate, turnDateTime, roundNum, downloadBlob, turnThousandth, turnNumberToFixed2, turnArrayKeys, getGkYear, hidePhoneFormat, groupByAndMergeChildArrays } from '../utils/index';
export { SEX_OPTIONS, SUBJECT_OPTIONS, FIRST_CHOICE_SCIENCES_OPTIONS, SECOND_CHOICE_SCIENCES_OPTIONS, ALL_OPTIONS, NO_LIMIT_OPTIONS, NO_LIMIT_NULL_OPTIONS, GK_DATE_OPTIONS, getYearOptions, routeMenuList, findOptions } from '../utils/options';
export { phoneRule, emailRule, numberRule } from '../utils/rules';
export { API_URLS } from '../utils/url';
export { useImage } from '../node_modules/@nuxt/image/dist/runtime/composables';
export { useSwiper, useSwiperSlide } from 'swiper/vue';
export { A11y as SwiperA11y, Autoplay as SwiperAutoplay, Controller as SwiperController, EffectCards as SwiperEffectCards, EffectCoverflow as SwiperEffectCoverflow, EffectCreative as SwiperEffectCreative, EffectCube as SwiperEffectCube, EffectFade as SwiperEffectFade, EffectFlip as SwiperEffectFlip, FreeMode as SwiperFreeMode, Grid as SwiperGrid, HashNavigation as SwiperHashNavigation, History as SwiperHistory, Keyboard as SwiperKeyboard, Manipulation as SwiperManipulation, Mousewheel as SwiperMousewheel, Navigation as SwiperNavigation, Pagination as SwiperPagination, Parallax as SwiperParallax, Scrollbar as SwiperScrollbar, Thumbs as SwiperThumbs, Virtual as SwiperVirtual, Zoom as SwiperZoom } from 'swiper/modules';
export { useDayjs } from '../node_modules/dayjs-nuxt/dist/runtime/composables/dayjs';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';