// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/30 09:53:47
const configMerger = require("D:/yue/Arco-Dawn/Nuxt-Web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/yue/Arco-Dawn/Nuxt-Web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/plugins/**/*.{js,ts,mjs}","D:/yue/Arco-Dawn/Nuxt-Web/composables/**/*.{js,ts,mjs}","D:/yue/Arco-Dawn/Nuxt-Web/utils/**/*.{js,ts,mjs}","D:/yue/Arco-Dawn/Nuxt-Web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/yue/Arco-Dawn/Nuxt-Web/app.config.{js,ts,mjs}"] }));

module.exports = config
