// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/9 14:28:02
const configMerger = require("C:/Users/二跃/Desktop/zs/高报/gb_web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/二跃/Desktop/zs/高报/gb_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/plugins/**/*.{js,ts,mjs}","C:/Users/二跃/Desktop/zs/高报/gb_web/composables/**/*.{js,ts,mjs}","C:/Users/二跃/Desktop/zs/高报/gb_web/utils/**/*.{js,ts,mjs}","C:/Users/二跃/Desktop/zs/高报/gb_web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/二跃/Desktop/zs/高报/gb_web/app.config.{js,ts,mjs}"] }));

module.exports = config
