// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/12/6 17:47:57
const configMerger = require("C:/gb_web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/gb_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/plugins/**/*.{js,ts,mjs}","C:/gb_web/composables/**/*.{js,ts,mjs}","C:/gb_web/utils/**/*.{js,ts,mjs}","C:/gb_web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/gb_web/app.config.{js,ts,mjs}"] }));

module.exports = config
