/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZsChart: typeof import('./components/zsChart/index.vue')['default']
    ZsContent: typeof import('./components/zsContent/index.vue')['default']
    ZsDynamicTime: typeof import('./components/zsDynamicTime/index.vue')['default']
    ZsEditPassword: typeof import('./components/zsEditPassword/index.vue')['default']
    ZsGlobalSetting: typeof import('./components/zsGlobalSetting/index.vue')['default']
    ZsMenu: typeof import('./components/zsMenu/index.vue')['default']
    ZsNavBar: typeof import('./components/zsNavBar/index.vue')['default']
    ZsSearchTableMould: typeof import('./components/zsSearchTableMould/index.vue')['default']
    ZsSelectAddress: typeof import('./components/zsSelectAddress/index.vue')['default']
    ZsTabBar: typeof import('./components/zsTabBar/index.vue')['default']
    ZsWEditor: typeof import('./components/zsWEditor/index.vue')['default']
  }
}
